### ISSUE TITLE
travis sphinx build problems with package-level freeze_iers

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#140]
As discovered in desihub/desisim#530, Travis sphinx builds have errors when `desiutil.iers.freeze_iers` is called at the package level (trackback below).  Although having "import blah" trigger running code is generally discouraged, in this case it is useful to `freeze_iers()` at the package-level so that we don't have to remember to call it in every function that might use `astropy.time.Time()` — we might catch them all now, but it is easy to forget when writing a new function.

  * Is there a way that this can be "fixed" in `desiutil.iers.freeze_iers()` so that it plays nicely with Travis sphinx builds?
  * If not, is there a sphinx config workaround that could be applied once per package to allow package-level running of freeze_iers?

Since @weaverba137 is on vacation today, I'm trying to fix desihub/desisim#530 tests by isolating freeze_iers() calls within the code (not package-level), but longer term I'd like to find a more robust solution for how to use this that would allow running it at the package level.

Traceback:

```
Warning, treated as error:
autodoc: failed to import module 'pixsim' from module 'desisim.batch'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/travis/miniconda/envs/test/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/desihub/desisim/py/desisim/batch/pixsim.py", line 32, in <module>
    from desisim import obs
  File "/home/travis/build/desihub/desisim/py/desisim/obs.py", line 28, in <module>
    import desisim.simexp
  File "/home/travis/build/desihub/desisim/py/desisim/simexp.py", line 13, in <module>
    freeze_iers()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/desiutil/iers.py", line 96, in freeze_iers
    table = Table.read(name, format='ascii.ecsv').filled()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/table/table.py", line 2525, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/io/registry.py", line 531, in read
    data = reader(*args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/io/ascii/connect.py", line 39, in io_read
    return read(filename, format=format, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/io/ascii/ui.py", line 353, in read
    dat = reader.read(table)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 1168, in read
    self.header.get_cols(self.lines)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/io/ascii/ecsv.py", line 127, in get_cols
    header = meta.get_header_from_yaml(lines)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/table/meta.py", line 326, in get_header_from_yaml
    from ..io.misc.yaml import AstropyLoader
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/io/misc/yaml.py", line 89, in <module>
    YAML_LT_3_12 = not minversion(yaml, '3.12')
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/utils/introspection.py", line 168, in minversion
    return parse_version(have_version) >= parse_version(version)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 130, in parse_version
    return packaging.version.Version(v)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by weaverba137** [comment]
@sbailey, I strongly discourage you from using `freeze_iers()` at the module level in any case.  I have also run into nasty bugs when code is called at import time.  It is specifically designed so that you can call it as many times as you want, and it remembers that it has already been called once.  So spread it about liberally.

In this specific case, I can see it's a Sphinx error, but it would be nice to have a link to the actual test that failed.

**Comment by sbailey** [comment]
Here's the travis build that failed:

https://travis-ci.org/github/desihub/desisim/jobs/674514609

which was triggered by commit [3040e98](https://github.com/desihub/desisim/pull/530/commits/3040e985fa9dfd555a2c38b3f9ebf70a4da2d83e) of desihub/desisim#530.

I agree that running code upon import is distasteful, but so is having any use of astropy.time.Time() triggering a URL download which I think is even more problematic.  It will be a maintenance fragility if we have to remember every time someone adds a new piece of code using `Time` (and/or `Coordinates`?) that they also have to `freeze_iers()` first.  The current situation of failed downloads is almost a good situation because at least we get a warning message, instead of it silently ruining scaling by having N>>1 MPI ranks all trying to download the same file simultaneously.

An example of the maintenance problem, in desisim PR #530 I moved a package-level `freeze_iers` call into each of the individual functions that was using `Time` in that package.  That got around the sphinx problem, but ended up causing the download problem again because some other piece of code somewhere in desisim (I don't yet know where) had been benefiting from that freeze_iers() in the import, and now is generating the warning messages again during the integration tests.  What a pain.

**Comment by weaverba137** [comment]
I will think about this, but I do not see an easy, short term solution.  Simply adding freeze_iers into functions where needed will take much, much less time than finding a solution to this.

**Comment by weaverba137** [comment]
Still thinking about this, here are some questions.

1. It sounds like this is only a significant problem in desisim, and this issue is not affecting pipeline operations at all.  Is that the case, or is it simply that pipeline problems remain undiscovered?
2. If that is the case, is there any actual urgency to this, assuming desisim is not actually used by the production pipeline?
3. Related to urgency, I notice this has not been added to any of our existing project boards.
4. This is still a vague idea, but one option would be to forbid all *direct* imports of `astropy.coordinates` and `astropy.time`, and only import them second-hand via a module of `desiutil` that could handle this in an appropriate way (which I don't know yet).

**Comment by weaverba137** [comment]
So if you dig down deep into that error reported by Sphinx, it's not actually caused by `freeze_iers()` itself, but by the imports that it triggers while attempting to run.  Ultimately it looks like a version mismatch, or absence of and installed version, of pyyaml.

As of today, 21 April, is this test still broken in master?  The first thing to try would be to add pyyaml to `CONDA_DEPENDENCIES` in the .travis.yml.

**Comment by sbailey** [comment]
> Still thinking about this, here are some questions.
> 
> 1. It sounds like this is only a significant problem in desisim, and this issue is not affecting pipeline operations at all.  Is that the case, or is it simply that pipeline problems remain undiscovered?

This was a problem for the spectro pipeline until desihub/desispec#895 added it to the `desi_proc` wrapper script.  However, it continued to be a problem when we wanted to debug individual steps that then didn't have the protection of the wrapper and triggered a download again.  We've been adding freeze_iers when we trip across these, e.g. desihub/desispec#957.

> 2. If that is the case, is there any actual urgency to this, assuming desisim is not actually used by the production pipeline?

It's not an urgent blocking factor, but it is a distracting maintenance headache.  e.g. the nightly integration tests are still triggering a download somewhere in some unit  or integration test and it appears that is being sent to stderr and pulled out by the cronjob and emailed.  I'm sure I could chase that down, but haven't spent the time.

> 3. Related to urgency, I notice this has not been added to any of our existing project boards.
> 4. This is still a vague idea, but one option would be to forbid all _direct_ imports of `astropy.coordinates` and `astropy.time`, and only import them second-hand via a module of `desiutil` that could handle this in an appropriate way (which I don't know yet).

I'd like to find a solution that fixes it once at the root, rather than requiring everyone to remember to always do something special ("always use `freeze_iers` before using `astropy.time`", or "don't use `astropy.time` but use `desiutil.time` instead").  e.g. ideally this would be fixed at the astropy level, with an environment variable or config file option that would prevent it from downloading in the first place.  Fixing it in astropy wouldn't solve the problem for our future installs, but would be better in the long run.

As of today, freeze_iers is sprinkled in enough places to prevent the sphinx problem with pyyaml, which I have only seen on Travis.  I tried to create the same environment locally and didn't get sphinx to fail and then moved on.  Unit or integration tests are still triggering the download somewhere but I don't know where.

**Comment by weaverba137** [comment]
So that sounds like the problem isn't actually related to whether `freeze_iers()` is called at the package level, or the module level, or the function level, but simply a matter of finding all possible places where it is needed.

Have you tried calling it at the *script* level?  For example:
```python
#!/usr/bin/env/python
from desiutil.iers import freeze_iers
freeze_iers()
import os
import sys
# ...
```
That one call should be good for the entire lifetime of the script, regardless of where it may be needed.  However once the script exits, all bets are off.

**Comment by sbailey** [comment]
Yes, for `desi_proc` we added it at the script level, but we haven't gone through and added that to every script in every repo, and unit tests and jupyter notebooks access the same algorithmic code without going via the scripts, etc.  I'm more concerned about future whack-a-mole: we might find all cases now (I just added two more to desisim and pushed to master...) but someone could easily and innocently add another script or use of `Time` and break it again.  In the future it will be more insidious because newer versions of astropy will silently succeed at the download without making it obvious that 1000 cores just took a minute downloading the same file...

Perhaps the bottom line is that I fundamentally disagree with the astropy design choice of downloading files on the fly without warning and apparently without a trivial way of turning that off by default.  And that is a cost of using astropy.

**Comment by weaverba137** [comment]
OK, I agree that the design choice is unfortunate, but in terms of this issue, what specific functionality do we need to implement in desiutil to solve this?  I get the sense this ticket not getting us pointed toward solutions that can be implemented in code.

**Comment by akremin** [comment]
At some point does it become more/equally practical to design lightweight
desiutil wrapper versions of these modules and require/strongly suggest the
use of those in place of direct astropy imports?

from astropy import time.           ->   from desiutil.astropywrap import
time
from astropy.time import Time.   ->  from desiutil.astropywrap.time import
Time

where the wrappers just import, freeze_iers(), and return?

It would have the additional "feature" (which can always turn into a bug)
of allowing us to backport functionality astropy decides to change/drop in
the future but that our code relies on.

**Comment by sbailey** [comment]
OK, this does seem to be devolving into me complaining about astropy; thanks for bringing us back.  Options:

1. Original request: fix things so that `freeze_iers` could be called at the package level once so that importing a package covers everything within it, instead of adding it to N>>1 scripts and functions both now and in the future.
  * the problem that triggered this issue has something to do with yaml dependencies and the travis environment, not a fundamental problem with calling it at the package level
  * calling code at the package level is generally discouraged however as an unexpected side-effect
2. desiutil wrapper of astropy imports to insert `freeze_iers` in between.  I'm concerned that this will continue to be a whack-a-mole problem with our distributed part-time developer team forgetting to do the non-obvious but "right" thing of importing the desiutil version instead.
3. live with it and sprinkle `freeze_iers` through multiple functions and scripts as needed.  This is defacto what we are doing now.
  * I'd like this better if we had some sort of unit test that could catch a new piece of code inadvertently triggering an astropy download by having some code path not call `freeze_iers` early enough.  I'm not sure how we'd do that.
4. live with it for now and put our resources into providing an option to astropy to turn off this behavior, e.g. via a ASTROPY_NO_DOWNLOAD environment variable that we could set in desimodules.
5. My preferred option would actually be if astropy fundamentally switched their design philosophy to "by default don't download anything on-the-fly" and you have to do something special to trigger an update of the parameter files.  I'm not optimistic that they would do that, even though it seems a requirement for "reproducible results".

All of these have their downsides. Other options or opinions?

I'm currently most curious about the possibility of a unit-test protected version of (3).  Any ideas for how to get an accidentally missed freeze_iers to trigger a failure instead of download?

**Comment by weaverba137** [comment]
OK, here are some additional thoughts on your points in order.

1. Let's be careful to use the term "module" not "package".  A module is a single .py file.  A package is a set of .py files in a directory that contains various `__init__.py` files.  With this option, you still have to add it to every *module* that could ever possibly contain `astropy.time` code.  That is, you can't guarantee that `from foo import blah` will call `freeze_iers()` unless it's actually in blah.py, or blah.py imports a module that calls `freeze_iers()`.  For a large package, that's just as much pain as inserting it at the function level.
2. I recognize that even expert developers can't be perfect all the time, but I think we could do better with due diligence at all levels: training, documentation, code review, unit testing, etc.
3. Astropy actually does have some functionality that looks for tests that try to download data, however in this particular case, because the functions were being called at import time, it bypassed that mechanism.  In other words, in order for the test to catch the attempted download, it actually has to happen during the test.  And the test has to exist of course.  This is definitely worth thinking about though.  An additional complication is that Astropy uses the pytest framework instead of unittest.
4. I did talk to various Astropy people about this.  One suggestion they offered was pre-seeding the equivalent of `~/.astropy` directories on the compute nodes, with appropriately modified configuration files, and environment variables set to point to that directory.  I think this would have to be done as part of a Slurm script before any Python code is run.  I thought just doing it in the Python code would be easier, but maybe not.
5. I think at least a few of them are starting to "get it" as far as high-performance computing environments are concerned, but the dominant design philosophy is still primarily "make things easy for the solo end-user doing one-off analysis so they'll be more likely to adopt Python."  We need more people from DESI besides myself agitating them.

I will do some more research on option 3.  Please think about the amount of work to implement option 4 as opposed to a code-based solution.  In particular, even though we could build the pre-seeding into a Slurm script, that might not apply to scripts run interactively.

**Comment by weaverba137** [comment]
This issue has been dormant since April and we should reconsider whether this is still an actual problem:

1. We have moved to Astropy 4, which handles IERS calls differently.
2. We will probably be abandoning Travis entirely in the near future.
3. No one has visibly complained about this since April.

@sbailey, can we just close this with no action?

**Comment by sbailey** [comment]
OK to close for now.  We continue to sprinkle freeze_iers throughout our code as a somewhat tedious but straightforward solution.  We're also still playing whack-a-mole with astropy downloading stuff without warning (leap seconds being another recent example), but this specific issue doesn't need to remain open.
