### ISSUE TITLE
Don't assume master is default branch

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#154]
In `desiInstall` and other functionality, allow the default git branch to be something other than `master`.

@sbailey, I believe the GitHub default for new repositories is to call the default branch `main`.  I think we should follow this convention.

**Comment by sbailey** [comment]
Yes, the default for new repos is "main" instead of "master", good.  For existing repos, https://github.com/github/renaming still recommends

> If you haven’t renamed your default branch yet, consider waiting until later this year. We’re investing in tools to make renaming the default branch of an existing repository a seamless experience for both maintainers and contributors.

They are running out of time for "later this year", but I'm still holding out for that "seamless experience" to ease the transition.  If someone is aware of other GitHub tools/documentation that supersedes those recommendations (which hasn't been updated in 2 months), let us know.
