### ISSUE TITLE
Move NERSC code into a software/code directory

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#32]
Currently our software layout at NERSC is:

* software/
  - cori/
  - edison/
  - ...
  - modules/
     * cori/
     * edison/
     * ...

It has been proposed to change this to.

* software/
   - code/
      * cori/
      * edison/
      * ...
  - modules/
     * cori/
     * edison/
     * ...

**Comment by weaverba137** [comment]
When this was first proposed I recall feeling a little trepidation; now I know why.  Changing this would not be particularly simple.

The problem is that almost every DESI module file contains this snippet:
```tcl
if {[info exists env(DESI_PRODUCT_ROOT)]} {
    set PRODUCT_ROOT $env(DESI_PRODUCT_ROOT)
} else {
    set PRODUCT_ROOT /project/projectdirs/desi/software/$env(NERSC_HOST)
}
set PRODUCT_DIR $PRODUCT_ROOT/$product/$version
```
I know the logic appears a bit backward here, but this is leftover from a time when we were assuming we would need to support module files on all possible platforms, not just NERSC.  So the logic is, "set the `DESI_PRODUCT_ROOT` environment variable to override the default NERSC value, which is hard-coded."  As a corollary of this logic, the desimodules product does *not* set `DESI_PRODUCT_ROOT`.

Also, keep in mind that despite changes in where we support Modules, we need to *retain* the ability to set `DESI_PRODUCT_ROOT` to override the default value, because that's how I'm able to install DESI software in a "from scratch" environment in order to run integration tests (*i.e.* desihub/desiutil#29).

So **IF** we adopt the new directory structure, do we:

- edit every existing module file *both* in GitHub *and* on disk, or,
- require that `DESI_PRODUCT_ROOT` is always set, even if it just points to the default location, and accept that there will occasionally be errors when people forget to set this when working in a non-standard environment.

I suspect the answer will probably be both: force everyone to always set `DESI_PRODUCT_ROOT` (by adding it to desitree, for example) during the period during which we're updating the module files for every DESI product.

**Comment by weaverba137** [comment]
@tskisner, @sbailey this issue is partially moot because `/project/projectdirs/desi/software` will hardly be used at all, except on datatran & scigate nodes.

1. Do we even *want* to support the full DESI software stack on datatran & scigate going forward?  I know I have requested it in the past, but that was more out of a desire to keep all systems in sync, rather than a particular software need.
2. If we *do* want that support, then it would be nice if `/project/projectdirs/desi/software` were reorganized to look more like `/global/common/$NERSC_HOST/contrib/desi`.

**Comment by tskisner** [comment]
The question I keep asking is:  What parts (if any) of the desi packages do we need to install and run on datatran.  For example, do some packages contain scripts to perform the data transfer?  If so, then that means we need to at least install those packages and their dependencies...

**Comment by sbailey** [comment]
datatran: we only *need* to support whatever is necessary for DTS to coordinate with our pipeline, which might not be anything if DTS always has to use grid/NEWT to launch commands on edison/cori anyway.  At the same time, it can be convenient to have the basic python codes available (desisim, desispec, and their dependencies).  Let's setup the directory structure so that we *could* support datatran, but not go overboard until we see what users (us) really want and add stuff as needed.

scigate: theoretical future needs, but nothing that we currently need AFAIK.  Possibilities include: surveyqa webapp and jupyter notebook.  Let's setup the directory structure so that this could be supported, but not enable it until we really need it.

Agreed about making the structure of `/project/projectdirs/desi/software/$NERSC_HOST` match the directory structure of `/global/common/$NERSC_HOST/contrib/desi`.  From our last conversation, I think this means that both of them would be a basic root directory  of `base=/project/projectdirs/desi/software/$NERSC_HOST/` or `base=/global/common/$NERSC_HOST/contrib/desi`, under which we would have:

  * `$base/conda/conda_{pyver}-{version}[_extra]` : new directories for conda environments and companion C++ conda_extra environments
  * `$base/modulefiles/{product}/{version}` : module definition files both both conda and individual packages like desiutil, desispec, etc.  Previously `$base/modules/{product}/{version}`
  * `$base/software/{product}/{version}` :  code for individual packages, installed "in-place" so that the `bin/` and `lib/` directories in there should be added to `$PATH` and `$PYTHONPATH`.  Or did we pick a different name than "software"?  Seems like a reasonable choice on contrib, but it has a double "software/$NERSC_HOST/software/" on project?  Do we care?  Previously `$base/{product}/{version}`

**Comment by weaverba137** [comment]
I cannot remember whether we decided on `$base/software` or something else.  I think `$base/code` had been suggested in the past.

Otherwise I agree with all of the above.

**Comment by weaverba137** [comment]
I'm moving forward on the desiutil update, but we never agreed on what to do about this problem with nearly every existing module file:

```tcl
if {[info exists env(DESI_PRODUCT_ROOT)]} {
    set PRODUCT_ROOT $env(DESI_PRODUCT_ROOT)
} else {
    set PRODUCT_ROOT /project/projectdirs/desi/software/$env(NERSC_HOST)
}
set PRODUCT_DIR $PRODUCT_ROOT/$product/$version
```

We will probably want to re-install all DESI software in the new location, rather than copy it, but we also can't just copy the existing module files.  We have to edit the module files in GitHub, cut new tags, then install.

Symlinks might help temporarily though.

**Comment by weaverba137** [comment]
And as a reminder: the existence of `DESI_PRODUCT_ROOT` is a signal to desiInstall that it is not running at NERSC at all.

**Comment by sbailey** [comment]
If we can deprecate but temporarily support the existing module files using symlinks, let's do that.  At some point when all of the currently installed packages are several versions old, we can remove them and do some special case editing if we really really need to reinstall an old tag.

On some other thread I suggested using the non-existence of $NERSC_HOST instead of the existence of $DESI_PRODUCT_ROOT as the sign that you're not at NERSC, and then adding to desiInstall a --prefix option to override what root should be used.  I think I still like that.  e.g. something like:
```
if --prefix is set, use that
else if $DESI_PRODUCT_ROOT is set, use that
else if $NERSC_HOST is set, use /global/common/$NERSC_HOST/contrib/desi/
else give up and raise error
```
If that could be handled at the level of desiInstall logic instead of internal to every module file, that could simplify installations (both official ones and test ones to a non-standard location), while also reducing the maintenance overhead for the module file.

**Comment by weaverba137** [comment]
That logic is possible, but as discussed in #42, that is adding to the complexity of desiInstall, or at the very least, adding to the work needed to just get the software installed in a different directory.

Also `else if $NERSC_HOST is set, use /global/common/$NERSC_HOST/contrib/desi/
` has to be more complicated than that because it looks like we'll never get `/global/common/datatran/contrib/desi`.
