### ISSUE TITLE
Any plan to upgrade the desiutil on CORI-NERSC

### ISSUE THREAD

**Issue by mehdirezaie** [desihub/desiutil#69]
Hi!

I was planning to use desitarget to do some target selection. I realized that the new version of desitarget relies on a newer version of desiutil. The most updated version of desiutil on cori is desiutil/1.3.5.
I was wondering if someone could give me a way around? I would really appreciate that.

Mehdi

**Comment by weaverba137** [comment]
You must be using an old software stack, because desiutil/1.9.3 is already installed on cori.

You should be initializing your DESI environment on all systems with 
```
source /global/project/projectdirs/desi/software/desi_environment.sh
```
assuming your shell is bash.

@sbailey, @tskisner, should we just remove any legacy cori & edison software in /project/projectdirs/desi/software at this point to force people to change?

**Comment by tskisner** [comment]
Fine with me.  Also there are a bunch of ancient conda environments in /global/common (pre-dating the desiconda package) that we should clean up.  I believe @sbailey was working on an update to desimodules that updates the tagged versions being loaded by desi_environment.sh.  I guess I'll wait until that is set before wiping those things.  However, the stuff on /project is even older and I agree should be removed.

**Comment by weaverba137** [comment]
Thanks, & PS, we would give a suitable warning before removing.

**Comment by mehdirezaie** [comment]
Thanks so much @weaverba137 , yes I was doing:
```
source /project/projectdirs/desi/software/modules/desi_environment.sh
```
