### ISSUE TITLE
tests fail on as-installed desiutil at NERSC

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#78]
desiutil tests pass, but they don't pass on a copy of desiutil as installed by desiInstall at NERSC.  Although normally one runs tests before installing, it is still helpful to be able to run tests post-installation to verify that the as-installed copies of code work before doing a final signoff on a set of tags for a desimodules release.  Most of our repos work with a post-install test; desiutil and desispec are the exceptions.

Works (testing a non-installed checkout of a tag):
```
source /project/projectdirs/desi/software/desi_environment.sh
module unload desiutil
git clone https://github.com/desihub/desiutil
cd desiutil && git checkout 1.9.5
python setup.py test
```

Fails on installed copy of same version of the code:
```
source /project/projectdirs/desi/software/desi_environment.sh
cd $DESIUTIL; python setup.py test
```

Traceback:
```
======================================================================
ERROR: test_get_version (desiutil.test.test_setup.TestSetup)
Test parsing a _version.py file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/code/desiutil/1.9.5/py/desiutil/test/test_setup.py", line 126, in test_get_version
    v = get_version(self.fake_name)
  File "/global/common/cori/contrib/desi/code/desiutil/1.9.5/py/desiutil/setup.py", line 224, in get_version
    update_version(productname)
  File "/global/common/cori/contrib/desi/code/desiutil/1.9.5/py/desiutil/setup.py", line 257, in update_version
    raise IOError("Could not determine repository type.")
OSError: Could not determine repository type.

======================================================================
ERROR: test_update_version (desiutil.test.test_setup.TestSetup)
Test creating and updating a _version.py file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/code/desiutil/1.9.5/py/desiutil/test/test_setup.py", line 137, in test_update_version
    os.makedirs(p)
  File "/global/common/cori/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/global/common/cori/contrib/desi/code/desiutil/1.9.5/frobulate'
```

**Comment by weaverba137** [comment]
At first pass, it looks like you're testing 1.9.5, not 1.9.6.  1.9.6 should be installed, but isn't necessarily the *default* on cori.

**Comment by sbailey** [comment]
Indeed, I first tripped on this with 1.9.6 under the new desiconda directory organization, but I also see the problem with 1.9.5 with our previous desiconda installation.  I quoted that older case for this ticket so that we don't mix up the new directory structure (not yet finalized / announced) with this issue which I think is independent of that.  You're welcome to debug it with either version.

**Comment by weaverba137** [comment]
I think I have a theory: that particular test may be assuming that it is running in a *git checkout*, which is true in both your own working copy & on Travis, but with a truly properly installed version, that assumption is invalid.  I don't think I can fix this immediately, maybe in a couple of days, but in the meantime, I think maybe you can ignore these failures.

**Comment by weaverba137** [comment]
This does not explain the test failure, but, for the record, running `python setup.py test` is not the normal way to test an already-installed Python package, because for a normally-installed package, the setup.py file will not be present.  This only works for DESI packages because we also copy the entire contents of the package to the install directory, in addition to running `python setup.py install`.

Because of this, running `python setup.py test` in an installed DESI package will most likely test the contents of the `py/` directory rather than the properly-installed `lib/python3.5/site-packages/` directory.

The best way to test a *tag* is to `git checkout <tag>` in a clone and run `python setup.py test` as you already did in the first example.

**Comment by weaverba137** [comment]
Hmm, and I see that the tests actually succeeded when you tested the tag.

The correct way to test an *installed* DESI package is
```
python -m desiutil.test.desiutil_test_suite
```
and in fact, that test produces a similar set of errors.

**Comment by weaverba137** [comment]
The `test_get_version` failure is due to the test code running in an installed environment, not a git or svn checkout.  Specifically, `desiutil.setup.update_version()` requires the presence of a `.git/` or `.svn/` directory.  The presence of these directories assures `update_version()` that it will be able to obtain the metadata it needs to set the `_version.py` file.

The `test_update_version` failure is a knock-on effect of `test_get_version` not cleaning up after itself after it failed.

**Comment by weaverba137** [comment]
Notes on how to reproduce this from a git checkout:

1. Make sure desiconda is the only thing in your `$PYTHONPATH`.
2. Starting from a git checkout (with tcsh bias, heh):
   ```
   mkdir ../desiutil_test
   cp -a py/ ../desiutil_test
   cd ../desiutil_test
   find py -name \*.pyc -delete
   find py -type d -name __pycache__ -delete
   setenv PYTHONPATH `pwd`/py:$PYTHONPATH
   python -m desiutil.test.desiutil_test_suite
   ```
