### ISSUE TITLE
raise desiInstall error if desimodel data is missing

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#89]
`desiInstall desimodel {version}` should fail if there isn't a matching data version in SVN.  Currently it silently installs the code without the data without any warnings or errors or non-zero return codes to indicate that the installed desimodel is problematic.

The fix might be for something on the desimodel side to raise an error that would get noticed by desiInstall.  I haven't looked under the hood.

I discovered this when trying to install desimodel/0.9.0 before remembering to make a matching svn tag.  That tag now exists so you'll need to make a fake code tag without a matching svn tag for reproducing/testing this.

**Comment by weaverba137** [comment]
Hmm, this requires some care, because while it is true that each desimodel tag in git should have a matching tag in svn, you also need to retain the capability to install svn branches, for testing, etc.

In fact if you look at https://github.com/desihub/desiutil/blob/5bc361fffe66f504c63e42286ca90ab8bd61dd70/py/desiutil/install.py#L885, you can see that errors were deliberately ignored at some point in the past.

If we turn back on the error handling, we will also have to set `$DESIMODEL_VERSION`, see https://github.com/desihub/desimodel/blob/master/etc/desimodel_data.sh.

**Comment by weaverba137** [comment]
OK, `$DESIMODEL_VERSION` should in fact be set by desiInstall normally.

**Comment by sbailey** [comment]
How about this for desimodel git vs. svn:
1. installing a git tag requires a matching svn tag
2. installing git master or a git branch installs svn trunk

I don't actually remember ever desiInstalling a desimodel branch so if that is at all messy I'm fine with deprecating that for now.  99% of the usage is to install a tag, and if that tag is broken by not having a matching svn tag, I would like desiInstall to fail loudly and informatively.

**Comment by weaverba137** [comment]
Ah, that jogged the memory a little bit.  I think item 2 was the tricky part, because the install script in desimodel (`etc/desimodel_data.sh`) is very simplistic.  When `DESIMODEL_VERSION` is set by desiInstall, the script does not try to translate that into a proper svn path, it just drops it directly into the svn URL.  When `DESIMODEL_VERSION` is set in .travis.yml, however, that is usually set to the correct svn path.

Which brings up another possible thing that we should test for:  The desimodel testing branch in svn should match the version of desimodel downloaded for the test.  In other words, if a Travis test wants desimodel tag 0.8.3, there should be a branches/test-0.8 in svn.
