### ISSUE TITLE
MPI logging stdout redirection incompatibility with desiutil logger?

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#98]
I've seen log messages like this recently in both two_percent_DESI/mini/wrap-redrock and desitarget/bin/mpi_select_mock_targets when using master desiutil and desispec:
```
--- Logging error ---
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/bin/mpi_select_mock_targets", line 159, in <module>
    healpixels=rankpix[i:i+n])
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/mock/build.py", line 347, in targets_truth
    nside=nside, nside_chunk=nside_chunk)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/mock/build.py", line 175, in read_mock
    MakeMock = getattr(mockmaker, '{}Maker'.format(target_name))(seed=seed)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/mock/mockmaker.py", line 2664, in __init__
    super(FAINTSTARMaker, self).__init__(seed=seed)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/mock/mockmaker.py", line 2301, in __init__
    flux, wave, meta = read_basis_templates(objtype='STAR')
  File "/global/common/cori/contrib/desi/desiconda/current/code/desisim/master/py/desisim/io.py", line 974, in read_basis_templates
    log.info('Reading {}'.format(infile))
Message: 'Reading /global/project/projectdirs/desi/spectro/templates/basis_templates/v2.4/star_templates_v2.1.fits'
Arguments: ()
```

These use code like
```python
from desispec.parallel import stdouterr_redirected
from desiutil.log import get_logger
log = get_logger()
logfile = '/path/to/some/file.log'
log.info('starting log redirection to {}'.format(logfile))
with stdouterr_redirected(to=logfile):
    log.info('blat')  #- should go to logfile instead of the screen
```

I'm not sure if the recent logging cleanup broke this or whether something changed in `stdouterr_redirected`.  Perhaps the `log` singleton is caching its stdout and not picking up on the swap that stdout is now going elsewhere?  We need to debug/fix this logging redirection combination.  For context, this is mostly used with an MPI program redirecting logging for each rank to a different file.

**Comment by tskisner** [comment]
I don't know what broke, but the stdout redirection context manager has not changed for a while.  This kind of log redirection is absolutely critical for the pipeline, since it is wrapping code which is not aware of the parallel way in which it is running (and hence prints a lot to stdout).  The redirection context manager should explicitly flush stdout before redirecting, so any unwanted caching (if that is the problem) would be happening at the higher level.

**Comment by weaverba137** [comment]
My initial assessment is that most Python logging handlers are buffered at some level, so that's something to look at.  @tskisner, when you say "happening at the higher level", is that the logging handler level?

Under the hood `desiutil.log` uses [logging.StreamHandler](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler), with no modifications, besides adding a formatter.

Maybe an explicit `.flush()` on the handler should happen when the context manager starts up?

**Comment by weaverba137** [comment]
OK, I *really* think we need to take a closer look at the context manager here, because it is manipulating the log object quite a bit more than I expected.  And in fact, it's manipulating it in a way that is no longer consistent with the existing log object as defined in `desiutil.log`.  I'm looking at https://github.com/desihub/desispec/blob/master/py/desispec/parallel.py#L313.

**Comment by weaverba137** [comment]
Also, looking at the context manager, I can't see where it reattaches the *old* handler for `sys.stdout` when the context manager exits.

**Comment by weaverba137** [comment]
I'm also going to put out an *opinion* here, that we should *always* log to a file, *never* to `sys.stdout` or `sys.stderr`, *unless* there is a critical error.  In other words, for automated processes, success should be defined as no output, except to files, with a zero (0) returned to the calling shell.

**Comment by weaverba137** [comment]
PS, to be clear, my previous comment applies to *production*, not to development/debugging.

In fact, that dichotomy actually suggests a solution:  have two types of loggers: the existing `desiutil.log.get_logger()` will get you a *development* logger; create a new type of logger, say `desiutil.log.get_pipeline_logger()` that only logs to files.  Alternatively, set an environment variable, say `$DESI_PRODUCTION` that, if set, causes `get_logger()` to return a file-based logger, rather than a stream logger.

**Comment by julienguy** [comment]
I like this idea of including an optional file logger in the desiutil.get_logger() system.
However, how can we set the log file path? 
 - an environment variable wouldn't work in a MPI job where we want each process to write to a different file.
 - a filename, specified for instance by get_logger(filename="...") would work, but how to preserve this when get_logger() is called from another routine?

**Comment by tskisner** [comment]
Also note that regardless of where the logger is writing (stdout or a file), the redirection to **per-process** files is necessary in order to not have many processes stomping on each other.

The pipeline can't control where functions it calls are writing.  However it **can** forcibly redirect stdout to prevent functions from doing "bad things".  Controlling this in a single place is much easier than going through thousands of lines of constantly changing code and trying to enforce policy.

I propose a simple change:
-  In the redirection context manager, save the state of the logger on enter
-  restore it on exit

Keep the existing behavior of redirecting stdout to per-process files (which are joined on exit) and creating a new logger that sits on top of that new stdout.  We should ensure that the logging level, etc, is preserved with the new logger.

**Comment by weaverba137** [comment]
And don't forget to `.flush()` the logger handler on enter, and *also* `.flush()` the replacement handler before it is removed and the original handler restored.

**Comment by tskisner** [comment]
Looking at the redirection code, I basically do:

1.  redirect stdout / stderr
2.  remove all handlers from the desi logger and add new ones that use the new stdout / stderr.
3.  At the end, redirect stdout / stderr to the original locations.
4.  ???  Never reset the desi logger handlers as I did in step 2.

I'll open a PR in the next couple days to address this (by actually doing number 4).

**Comment by tskisner** [comment]
I have now investigated this further.  The MPI log redirection has not changed and actually is doing the correctly intended thing (my previous comment was wrong).

Instead, I believe this breakage is due to a change in the logging introduced by ff24da7f7c7fdf44df5bfc45d4234ce9ac7eab6c.  Specifically, there used to be a single global desi logger instance.  I believe this was changed to return a new logger instance each time.

Here is how things used to work:

1.  Code path enters log redirection.  Get the *global* desi logger instance and replace all handlers to write to new stdout.

2.  Wrapped code runs.  Some of this code uses the global desi logger and the output is transparently written to disk.

3.  Code path reaches end of log redirection and global desi logger has its handlers replaced with the original stdout.

Now that we no longer have a global logger / singleton instance, here is what happens:

1.  Code path enters log redirection.  Gets a new desi logger instance and replaces all handlers to write to new stdout.

2.  Wrapped code runs.  Some of this code gets a new desi logger (different from 1) and uses it.  This new instance of a desi logger knows nothing about the logger created and modified in step 1.

3.  Code path reaches end of log redirection reverts its logger instance to stdout.

So moving from a global logger instance means that we can't modify that logger and have the changes inherited by downstream code.  I'm not sure the motivation of moving away from a global logging singleton, so I guess I'm not sure of the best approach moving forward.  However, I can definitely say that getting log redirection working again is a critical requirement for running pipelines at scale.

**Comment by julienguy** [comment]
I agree it's a priority we have this running. I don't remember what was the motivation for having a "new logging backend infrastructure".

**Comment by weaverba137** [comment]
@tskisner, I don't think you have read the `desiutil.log` code closely enough.  It still returns a singleton.  It just selects from a *suite* of singletons, based on the log level, and details of the log formatting options.

**Comment by tskisner** [comment]
Ok, so that means that if any of the wrapped code uses a different logger than the default one grabbed by the redirection context manager, then it will break.

So I guess I need to loop over that set of loggers and redirect all of them?

**Comment by tskisner** [comment]
Ok, I see now the _desiutil_log_root dictionary.  So I guess I can just loop over that and redirect everything.  As long as that dictionary does not have any new items added by the wrapped code...

**Comment by tskisner** [comment]
And of course if an of the wrapped code used the "timestamp" option, that would create a new unique root logger with its output un-redirected.

**Comment by weaverba137** [comment]
@tskisner, I am also concerned that you don't appear to have addressed the need for explicit `.flush()`, unless that's already been implemented?

**Comment by tskisner** [comment]
Yes, all streams are flushed before redirection and flushed again before being directed back.  Both the C-level streams:

https://github.com/desihub/desispec/blob/master/py/desispec/parallel.py#L284

And the python wrappers (close method does a flush):

https://github.com/desihub/desispec/blob/master/py/desispec/parallel.py#L293

**Comment by weaverba137** [comment]
OK, thanx for confirming that.

**Comment by tskisner** [comment]
I'm guessing the timestamp log feature is mainly a way to create a new, guaranteed-to-be-unique logger.  As long as we don't use that in the pipeline code that is being redirected, then I think we are fine.  My only concern is if we forget that rule of thumb down the road some time.

I'll go ahead and implement redirecting all the loggers in the global dictionary.  I'll save the list of keys at the initial redirection, and if that list of keys is different at the end, then I'll raise an exception.

**Comment by weaverba137** [comment]
No, all the loggers are already guaranteed to be unique.  The timestamp feature inserts a timestamp into the log message.  In other words it is a formatting feature.  Again, I recommend you re-read the code in its entirety.

**Comment by sbailey** [comment]
As a reminder, the motivation for having a suite of singletons (one for each log-level) was that previously if any piece of code requested a DEBUG logger, then all subsequent loggers would become DEBUG level.  We wanted to be able to turn on DEBUG logging locally in a function without it having a global side effect.

It looks like `_desiutil_log_root` is filled on demand when a new loglevel is requested, so as currently implemented it could change after the redirection has started.  We should probably update that to fill in loggers for each of DEBUG, INFO, WARNING, ERROR, CRITICAL at the start.

Consider also move this log re-direction logic into `desitutil.log` itself to keep the moving parts near each other.

**Comment by tskisner** [comment]
@weaverba137 , thanks for pointing that out.  @sbailey , I like the idea of pre-populating the logger singletons for all possible log levels.  That would make it guaranteed that everything gets redirected.

As for moving the redirection code- this context manager is MPI-aware (it takes a Comm argument, although does not explicitly import mpi4py).  Not sure it should go into desiutil, *unless* other desi packages need to use it.  In that case, it might make sense to move the entire parallel.py file into desiutil, since there are other utilities that might be useful as well.
