### ISSUE TITLE
Do we still need separate KNL support?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#99]
My understanding is that recent versions of desiconda are compiled in such a way that both haswell and knl are supported.  Thus it is no longer necessary to support separate cori and coriknl installations.  Can we confirm this?  It would simplify desiInstall a little bit.

**Comment by sbailey** [comment]
Reassigning to @tskisner because I don't know for sure.  It certainly would be preferable to have a single cori config that works for both.

**Comment by tskisner** [comment]
Sorry I missed this until now.  It is true that currently I'm building "fat" libraries / binaries on cori with the Intel compiler (-xAVX -axMIC-AVX512) so there *should* be runtime selection between normal AVX support and the AVX512 supported by KNL.  So as long as we are ok with that, then yes, we can just support a single "cori" software stack.  Since we have very little explicitly compiled code, I think we are more concerned with the particulars of how python and its packages are built.

**Comment by weaverba137** [comment]
OK, but there's still fiberassign, and any DESI packages that may (if not now, in the future) include Cython code.  What do we do about those?

**Comment by weaverba137** [comment]
@tskisner, Ping!

**Comment by weaverba137** [comment]
Based on discussions with @sbailey, I'm closing this with the answer "No, we no longer need coriknl support".
